### ISSUE TITLE
Curl error not catched properly?

### ISSUE THREAD

**Issue by Mindavi** [hhsnopek/beeroclock#4]
When I try to load the page, this is what I saw: https://gist.github.com/Mindavi/f55f4445644464dc40b4628db74cbfbb. 
Seems like the error from curl gets printed before the header.

**Comment by hhsnopek** [comment]
Looks like the location request sometimes dies/gets hung up
`curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.`

I thought I saw something similar earlier on when traffic first hit, but disregarded it initially. The curl request needs to be checked and if it fails for whatever reason, the service should fall back to UTC

**Comment by Mindavi** [comment]
Don't think this is relevant anymore, as this project hasn't seen any updates. Closing.
